### ISSUE TITLE
crash when enter the world

### ISSUE THREAD

**Issue by 2781762845** [Cadiboo/NoCubes#38]
This is the crash log
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2019-06-11 17:50:17 CST
Description: Rendering faces for smooth block in world

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Buffer.java:546)
    at java.nio.DirectByteBuffer.putFloat(DirectByteBuffer.java:897)
    at net.minecraft.client.renderer.BufferBuilder.pos(BufferBuilder.java:633)
    at io.github.cadiboo.nocubes.client.render.MeshRenderer.renderFaces(MeshRenderer.java:421)
    at io.github.cadiboo.nocubes.client.render.MeshRenderer.renderMesh(MeshRenderer.java:117)
    at io.github.cadiboo.nocubes.client.render.RenderDispatcher.renderTerrain(RenderDispatcher.java:325)
    at io.github.cadiboo.nocubes.client.render.RenderDispatcher.renderChunk(RenderDispatcher.java:190)
    at io.github.cadiboo.nocubes.client.render.RenderDispatcher.renderChunk(RenderDispatcher.java:117)
    at io.github.cadiboo.nocubes.hooks.Hooks.preIteration(Hooks.java:37)
    at net.minecraft.client.renderer.chunk.RenderChunk.rebuildChunk(RenderChunk.java:240)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.processTask(SourceFile:100)
    at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Cadiboo** [comment]
Should be fixed in later versions

**Comment by 2781762845** [comment]
Thank you.it's OK now
