### ISSUE TITLE
Nocubes 1.12.2-0.4.0PRE1 will crash in a Beta+ generated world

### ISSUE THREAD

**Issue by Shadowex3** [Cadiboo/NoCubes#64]
Full log is available [Here](https://paste.ee/p/l92Ye). Loading into a world already generated may work for a few seconds up to maybe even a minute or so but something about chunk generation goes haywire. Creating a new world crashes before entering the game.

**Comment by Cadiboo** [comment]
```
[07:11:56] [Server thread/INFO] [FML]: Loading dimension 0 (bare world test) (net.minecraft.server.integrated.IntegratedServer@770fc61e)
[07:11:56] [Server thread/INFO] [minecraft/AdvancementList]: Loaded 488 advancements
[07:11:56] [Server thread/WARN] [minecraft/WorldServer]: Unable to find spawn biome
[07:11:56] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:888) ~[oo.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:135) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.world.chunk.ChunkPrimer.func_177855_a(SourceFile:21) ~[ayw.class:?]
	at com.mrburgerUS.betaplus.beta_plus.util.DeepenOceanUtil.deepenOcean(DeepenOceanUtil.java:58) ~[DeepenOceanUtil.class:?]
	at com.mrburgerUS.betaplus.beta_plus.ChunkGeneratorBeta.func_185932_a(ChunkGeneratorBeta.java:114) ~[ChunkGeneratorBeta.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:310) ~[amu.class:?]
	at net.minecraft.world.World.func_175726_f(World.java:305) ~[amu.class:?]
	at net.minecraft.world.World.func_180495_p(World.java:911) ~[amu.class:?]
	at net.minecraft.world.World.func_175623_d(World.java:230) ~[amu.class:?]
	at net.minecraft.world.World.func_184141_c(World.java:210) ~[amu.class:?]
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76) ~[aym.class:?]
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944) ~[oo.class:?]
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866) ~[oo.class:?]
	... 4 more
```
Caused by an error in beta+ [here](https://github.com/mrburger/Beta-Plus/blob/b0b1997053c9a4fdc5968be0c8677b247b6647ce/src/main/java/com/mrburgerUS/betaplus/beta_plus/util/DeepenOceanUtil.java#L58).
NoCubes doesn't touch chunk generation so I have no clue how this could happen.
Are you sure that this only happens when NoCubes is installed? Have you tried without OptiFine?

**Comment by Shadowex3** [comment]
At your suggestion I just did to be absolutely sure, logs are [here ](https://paste.ee/p/Un9rY)and the same error happens. 

I'll admit I know nothing about Java so I'm probably so off it's not even wrong: Both mods work fine on their own, and only crash together, meaning it's definitely an interaction between the two occurring at chunk generation. Is it possible for Beta+ and Nocubes to get caught on each other, with nocubes trying to smooth out something Beta+ is in the process of generating? Or similar to #40 can beta+ give nocubes something that it can't handle and the math goes nuts trying to smooth it?

Also is there a way I can get you more detailed logs, maybe something that actually records what went wrong as it happened?

**Comment by Cadiboo** [comment]
Whats happening is that beta+ is trying to set a block state for one chunk in another chunk.
Unmapped stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.world.chunk.ChunkPrimer.func_177855_a(SourceFile:21)
	at com.mrburgerUS.betaplus.beta_plus.util.DeepenOceanUtil.deepenOcean(DeepenOceanUtil.java:58)
	at com.mrburgerUS.betaplus.beta_plus.ChunkGeneratorBeta.func_185932_a(ChunkGeneratorBeta.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.world.World.func_72964_e(World.java:310)
	at net.minecraft.world.World.func_175726_f(World.java:305)
	at net.minecraft.world.World.func_180495_p(World.java:911)
	at net.minecraft.world.World.func_175623_d(World.java:230)
	at net.minecraft.world.World.func_184141_c(World.java:210)
	at net.minecraft.world.WorldProvider.func_76566_a(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.func_73052_b(WorldServer.java:944)
	at net.minecraft.world.WorldServer.func_72963_a(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:123)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
```
Mapped stack trace:
```
java.lang.ArrayIndexOutOfBoundsException: -1
	at net.minecraft.world.chunk.ChunkPrimer.setBlockState(SourceFile:21)
	at com.mrburgerUS.betaplus.beta_plus.util.DeepenOceanUtil.deepenOcean(DeepenOceanUtil.java:58)
	at com.mrburgerUS.betaplus.beta_plus.ChunkGeneratorBeta.generateChunk(ChunkGeneratorBeta.java:114)
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:143)
	at net.minecraft.world.World.getChunk(World.java:310)
	at net.minecraft.world.World.getChunk(World.java:305)
	at net.minecraft.world.World.getBlockState(World.java:911)
	at net.minecraft.world.World.isAirBlock(World.java:230)
	at net.minecraft.world.World.getGroundAboveSeaLevel(World.java:210)
	at net.minecraft.world.WorldProvider.canCoordinateBeSpawn(WorldProvider.java:76)
	at net.minecraft.world.WorldServer.createSpawnPosition(WorldServer.java:944)
	at net.minecraft.world.WorldServer.initialize(WorldServer.java:866)
	at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:123)
	at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
```

There is no way that NoCubes should have anything to do with this as it doesn't touch anything to do with world generation or chunks.

**Comment by Shadowex3** [comment]
Well I just re-tested both individually with absolutely no other mods, not even optifine, and they each work individually. Notrace can work on a map initially generated with beta+ if beta+ is unloaded.

**Comment by Cadiboo** [comment]
I'll try and test this myself. You're using
```
Forge: 14.23.5.2847
NoCubes-1.12.2-0.4.0-pre1
betaplus-0.4.1
```

**Comment by Shadowex3** [comment]
Yes, everything right off of curseforge with Forge itself from MultiMC5. Is there are another diagnostic data that could be relevant or affect this? Java version?

**Comment by Cadiboo** [comment]
Your Java version is `1.8.0_152(x64)` but I really hope that doesn't have anything to do with this.
