### ISSUE TITLE
When I use this mod, my some plugin cannot be loaded

### ISSUE THREAD

**Issue by TLOvO** [Cadiboo/NoCubes#95]
**NoCubes 1.12.2-0.4.0-pre3
Minecraft Server 1.12.2 Mohist**

`[18:04:52 INFO]: Loading library org.yaml:snakeyaml:1.32
[18:04:53 WARN]: [MsLibrary] File: plugins\MsLibrary\kether.yml
[18:04:53 WARN]: com.luxun.mslibrary.taboolib.common.inject.ClassVisitException: class com.luxun.mslibrary.taboolib.module.kether.ScriptService#locale: VisitorGroup{priority=1, list=[com.luxun.mslibrary.taboolib.module.configuration.ConfigLoader@a995fad]} (INIT)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:124)[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:103)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:63)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:179)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:74)
[18:04:53 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:04:53 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:53 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:53 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:04:53 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:04:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84)
[18:04:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126)
[18:04:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323)
[18:04:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245)
[18:04:53 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392)
[18:04:53 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339)
[18:04:53 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315)
[18:04:53 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[18:04:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:04:53 WARN]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: YAML parsing failed
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:56)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:160)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:148)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:42)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.Configuration$Companion.loadFromFile(Configuration.kt:109)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.Configuration$Companion.loadFromFile$default(Configuration.kt:106)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigLoader.visit(ConfigLoader.kt:40)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:122)[18:04:53 WARN]:        ... 19 more
[18:04:53 WARN]: Caused by: java.lang.NullPointerException
[18:04:53 WARN]:        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
[18:04:53 WARN]:        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.AbstractCommentedConfig.setComment(AbstractCommentedConfig.java:94)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.CommentedConfig.setComment(CommentedConfig.java:27)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.setComment(ConfigSection.kt:248)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.setComments(ConfigSection.kt:252)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.addComments(ConfigSection.kt:258)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:95)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:79)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.loadFromString(YamlParser.kt:70)[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:54)
[18:04:53 WARN]:        ... 28 more
[18:04:53 WARN]: [MsLibrary] File: plugins\MsLibrary\config.yml
[18:04:53 WARN]: com.luxun.mslibrary.taboolib.common.inject.ClassVisitException: class com.luxun.mslibrary.ServerInfo#config: VisitorGroup{priority=1, list=[com.luxun.mslibrary.taboolib.module.configuration.ConfigLoader@a995fad]} (INIT)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:124)[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:103)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:63)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:179)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:74)
[18:04:53 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:04:53 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:53 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:53 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:04:53 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:04:53 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84)
[18:04:53 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126)
[18:04:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323)
[18:04:53 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245)
[18:04:53 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392)
[18:04:53 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339)
[18:04:53 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315)
[18:04:53 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[18:04:53 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:04:53 WARN]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: YAML parsing failed
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:56)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:160)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:148)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:42)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.Configuration$Companion.loadFromFile(Configuration.kt:109)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.Configuration$Companion.loadFromFile$default(Configuration.kt:106)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigLoader.visit(ConfigLoader.kt:40)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:122)[18:04:53 WARN]:        ... 19 more
[18:04:53 WARN]: Caused by: java.lang.NullPointerException
[18:04:53 WARN]:        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
[18:04:53 WARN]:        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.AbstractCommentedConfig.setComment(AbstractCommentedConfig.java:94)
[18:04:53 WARN]:        at com.electronwill.nightconfig.core.CommentedConfig.setComment(CommentedConfig.java:27)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.setComment(ConfigSection.kt:248)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.setComments(ConfigSection.kt:252)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.ConfigSection.addComments(ConfigSection.kt:258)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:95)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:79)
[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.loadFromString(YamlParser.kt:70)[18:04:53 WARN]:        at com.luxun.mslibrary.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:54)
[18:04:53 WARN]:        ... 28 more
[18:04:57 WARN]: [MsAction] Source:
COMMAND-TEMPLATES: "&c[MsAction] &7当前可用动作模板节点: {0}"
COMMAND-INFO: "&c[MsAction] &7当前注册的按键: {0}"
COMMAND-RELOAD: "&c[MsAction] &7重载成功 耗时 {0} 毫秒"
[18:04:57 WARN]: com.github.aosika3324.msaction.taboolib.common.inject.ClassVisitException: class com.github.aosika3324.msaction.taboolib.module.lang.Language#reload: VisitorGroup{priority=0, list=[AwakeFunction(lifeCycle=CONST), AwakeFunction(lifeCycle=INIT), AwakeFunction(lifeCycle=LOAD), AwakeFunction(lifeCycle=ENABLE), AwakeFunction(lifeCycle=ACTIVE), AwakeFunction(lifeCycle=DISABLE), com.github.aosika3324.msaction.taboolib.common.platform.ScheduleLoader@45d2b6c4, com.github.aosika3324.msaction.taboolib.common.platform.command.SimpleCommandRegister@739b1a9e, com.github.aosika3324.msaction.taboolib.platform.compat.PlaceholderExpansion$PlaceholderRegister@38889f82, com.github.aosika3324.msaction.taboolib.common.platform.event.EventBus@604ad277, com.github.aosika3324.msaction.taboolib.module.kether.KetherLoader@307e3c2c]} (INIT)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:136)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:104)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:63)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:179)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:74)
[18:04:57 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:04:57 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:57 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:57 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:04:57 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:04:57 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84)
[18:04:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126)
[18:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323)
[18:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245)
[18:04:57 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392)
[18:04:57 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339)
[18:04:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315)
[18:04:57 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[18:04:57 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:04:57 WARN]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: YAML parsing failed
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:56)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:66)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigFile.loadFromString(ConfigFile.kt:55)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.Configuration$Companion.loadFromString(Configuration.kt:139)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.Configuration$Companion.loadFromString$default(Configuration.kt:136)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.lang.ResourceReader.<init>(ResourceReader.kt:35)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.lang.ResourceReader.<init>(ResourceReader.kt:24)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.lang.Language.reload(Language.kt:102)
[18:04:57 WARN]:        at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.library.reflex.JavaClassMethod.invoke(JavaClassMethod.kt:31)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.platform.AwakeFunction.visit(AwakeFunction.kt:13)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.visitMethod(VisitorHandler.java:134)
[18:04:57 WARN]:        ... 19 more
[18:04:57 WARN]: Caused by: java.lang.NullPointerException
[18:04:57 WARN]:        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
[18:04:57 WARN]:        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.AbstractCommentedConfig.setComment(AbstractCommentedConfig.java:94)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.CommentedConfig.setComment(CommentedConfig.java:27)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.setComment(ConfigSection.kt:248)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.setComments(ConfigSection.kt:252)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.addComments(ConfigSection.kt:258)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:95)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.loadFromString(YamlParser.kt:70)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:54)
[18:04:57 WARN]:        ... 30 more
[18:04:57 WARN]: [MsAction] File: plugins\MsAction\kether.yml
[18:04:57 WARN]: com.github.aosika3324.msaction.taboolib.common.inject.ClassVisitException: class com.github.aosika3324.msaction.taboolib.module.kether.ScriptService#locale: VisitorGroup{priority=1, list=[com.github.aosika3324.msaction.taboolib.module.configuration.ConfigLoader@7937704a]} (INIT)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:124)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.inject(VisitorHandler.java:103)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.injectAll(VisitorHandler.java:63)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:179)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.TabooLibCommon.lifeCycle(TabooLibCommon.java:117)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.platform.BukkitPlugin.<init>(BukkitPlugin.java:74)
[18:04:57 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:04:57 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:57 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:04:57 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:04:57 WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:04:57 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:84)
[18:04:57 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:126)
[18:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:323)
[18:04:57 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:245)
[18:04:57 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:392)
[18:04:57 WARN]:        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:339)
[18:04:57 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315)
[18:04:57 WARN]:        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590)
[18:04:57 WARN]:        at java.lang.Thread.run(Unknown Source)
[18:04:57 WARN]: Caused by: com.electronwill.nightconfig.core.io.ParsingException: YAML parsing failed
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:56)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:160)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:148)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigFile.loadFromFile(ConfigFile.kt:42)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.Configuration$Companion.loadFromFile(Configuration.kt:109)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.Configuration$Companion.loadFromFile$default(Configuration.kt:106)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigLoader.visit(ConfigLoader.kt:40)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.common.inject.VisitorHandler.visitField(VisitorHandler.java:122)
[18:04:57 WARN]:        ... 19 more
[18:04:57 WARN]: Caused by: java.lang.NullPointerException
[18:04:57 WARN]:        at java.util.concurrent.ConcurrentHashMap.putVal(Unknown Source)
[18:04:57 WARN]:        at java.util.concurrent.ConcurrentHashMap.put(Unknown Source)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.AbstractCommentedConfig.setComment(AbstractCommentedConfig.java:94)
[18:04:57 WARN]:        at com.electronwill.nightconfig.core.CommentedConfig.setComment(CommentedConfig.java:27)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.setComment(ConfigSection.kt:248)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.setComments(ConfigSection.kt:252)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.ConfigSection.addComments(ConfigSection.kt:258)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:95)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlCommentLoader.fromNodeTree(YamlCommentLoader.java:79)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.loadFromString(YamlParser.kt:70)
[18:04:57 WARN]:        at com.github.aosika3324.msaction.taboolib.module.configuration.YamlParser.parse(YamlParser.kt:54)
[18:04:57 WARN]:        ... 28 more`

**Comment by Cadiboo** [comment]
Please share the full crash report

**Comment by TLOvO** [comment]
[latest.log](https://github.com/Cadiboo/NoCubes/files/10430529/latest.log)

**Comment by Cadiboo** [comment]
Fixed in 6e0a92b.  A new 1.12.2 release with the fix will be published soon.
